### PR TITLE
add greater and less support for compatible elasticsearch lucene syntax 

### PR DESCRIPTION
**Pull request by bigpigeon**
elasticsearch lucene syntax
https://www.elastic.co/guide/en/elasticsearch/reference/8.9/query-dsl-query-string-query.html#query-string-syntax

but only support

age:>10
age:>=10
age:<10
age:<=10
not support

age:(>=10 AND <20)
age:(+>=10 +<20)

## fix bug about below case 

```
age:>10 AND age:< 20
age:>=10 AND age:<= 20
```

### CODE REVIEW

**Comment by bigpigeon** [comment]
> I am not sure what is going on with github but I can't merge the changes from https://github.com/grindlemire/go-lucene/tree/pr-5-changes into this branch. It just has one extra commit on top of yours. Can you merge that into your branch here?

ok, I remerge your commit and take a new pr again ,wait

**Comment by grindlemire** [comment]
Another way to do that is for you to just pull my branch into yours and then push to yours and keep this PR. So:

```bash
git remote add upstream git@github.com:grindlemire/go-lucene.git
git fetch upstream
git pull upstream pr-5-changes
git push origin main
```

**Comment by bigpigeon** [comment]
> Another way to do that is for you to just pull my branch into yours and then push to yours and keep this PR. So:
> 
> ```shell
> git remote add upstream git@github.com:grindlemire/go-lucene.git
> git fetch upstream
> git pull upstream pr-5-changes
> git push origin main
> ```

thanks , I have followed the steps above

**Comment by grindlemire** [comment]
Thanks for contributing! I'll look into expanding support to include 

```
age:(>=10 AND <20)
age:(+>=10 +<20)
```

and then cut a new release.

**Pull request merged**
