### PR TITLE
Don't generate invalid postgres statements

### PR DESCRIPTION
**Pull request by erikdubbelboer**
Fuzz test using the postgres query parser to make sure we always generate valid statements.

This should greatly increase the safety but doesn't guarantee that it can't generate a valid postgres expression that could still be used to generate unsafe queries.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
This still doesn't fix everything, after fuzzing for a while it found `0:[0:* TO 0}` which compiles to `0 BETWEEN 0 SIMILAR TO '%' AND 0` which is not valid. This one I'm not sure how to fix as the the code for `Range` actually uses `()` in it's logic.

**Comment by grindlemire** [comment]
Thanks for the PR! I'll review this over the next couple days though at a high level it looks good to me. One thing to note is that I have been trying really hard to introduce no dependencies in this library to make it simple to include in any project without fear of bloat. This PR would introduce a library that itself includes protobuf. Would it be possible to remove that dependency? It looks like the library is only used in a test to validate that the generated sql is in fact valid sql. Perhaps there is another way we could achieve this?

**Comment by erikdubbelboer** [comment]
The dependency is only needed for testing and won't get compiled for users of the library.

**Comment by grindlemire** [comment]
Sure that is true. Can you add a comment to the go.mod for that dep specifying it is used only for testing?

**Comment by erikdubbelboer** [comment]
Done.

**Comment by grindlemire** [comment]
Sorry just got back around to this. LGTM. Thanks for contributing!

**Pull request merged**
